# 1. Import the necessary libraries

In [1]:
import nltk
import string
import re

In [2]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\alexandre.karneff\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Package punkt_tab is already up-to-date!

True

# 2. Text Normalization

In [3]:
# 1. lowercasing 
def text_lowercase(text):
    return text.lower()

In [4]:
input_text = "Hey, did you know that the summer break is coming? Amazing right !! It's only 5 more days !!"
input_text2 = "HeLlO, thIs Is deFiniTeLY well WriTTeN."
print(text_lowercase(input_text))
print(text_lowercase(input_text2))

hey, did you know that the summer break is coming? amazing right !! it's only 5 more days !!
hello, this is definitely well written.

In [5]:
# 2. Handling Contractions
import contractions

In [6]:
def fix_contractions(data):
    expanded_corpus = [contractions.fix(text) for text in data]
    return expanded_corpus

In [7]:
corpus = [
    "I can't wait for the new season of my favorite show",
    "I wanna be a great singer",
    "Let's go Mario !!",
    "I'd like a cup of tea",
    "we ain't like that"
    
]

In [8]:
fix_contractions(corpus)

['I cannot wait for the new season of my favorite show',
 'I want to be a great singer',
 'Let us go Mario !!',
 'I would like a cup of tea',
 'we are not like that']

In [9]:
# 3. Spell Checking
from autocorrect import Speller

def correct_with_autocorrect(text, lang="en"):
    # Correct spelling using autocorrect library for English.
    spell = Speller(lang=lang)
    return spell(text)

In [10]:
text = "I wnt to the librry to reed a bok"
corrected = correct_with_autocorrect(text=text)

In [11]:
print (f"Original : {text}")
print (f"Corrected : {corrected}")

Original : I wnt to the librry to reed a bok
Corrected : I wnt to the library to reed a bok

In [12]:
from textblob import TextBlob

In [13]:
def correct_with_textblob(text):
    blob = TextBlob(text)
    corrected = blob.correct()
    return str(corrected)

In [14]:
text = "I wnt to the librry to reed a bok"
corrected = correct_with_textblob(text=text)

In [15]:
print (f"Original : {text}")
print (f"Corrected : {corrected}")

Original : I wnt to the librry to reed a bok
Corrected : I went to the library to reed a boy

In [16]:
text = "Thsi is not a corect text I juste wote"
corrected = correct_with_textblob(text=text)

In [17]:
corrected

'His is not a correct text I just wrote'

In [18]:
from pyaspeller import YandexSpeller
speller = YandexSpeller()
fixed = speller.spelled('I wnt to the librry to reed a bok')
fixed

'I want to the library to read a book'

In [19]:
fixedtoo = speller.spelled('Thsi is not a corect text I juste typod')
fixedtoo

'This is not a correct text I just typed'

In [20]:
from pyaspeller import Word
check = Word('librry')
check.correct

c:\Users\alexandre.karneff\Documents\GitHub\NLP\.envnlp\Lib\site-packages\pyaspeller\word.py:18: UserWarning: Class Word is deprecated. Use YandexSpeller().spelled(text) instead
  warnings.warn("Class Word is deprecated. Use YandexSpeller().spelled(text) instead")

False

In [21]:
check.variants

['library', 'elibrary', 'libry']

In [22]:
check.spellsafe

'library'

# 3. Standardizing Accent Characters

In [23]:
import unicodedata

In [24]:
def standardize_accented_chars(text):
    return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')

In [25]:
input_text_accents = "Sômè words such as résumé, café, prôtest, divorcé, côordinâte, exposé, lattë"
print(standardize_accented_chars(input_text_accents))

Some words such as resume, cafe, protest, divorce, coordinate, expose, latte

# 4. Noise Removal

In [26]:
# 1. Removing HTML tag

def remove_html_tags_regex(text):
    #remove html tags using regex
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [27]:
html_text = "<p>Hello, <b>world</b>!</p> <a href ='#' >Click here</a>"
cleaned_html = remove_html_tags_regex(html_text)
print(cleaned_html)

Hello, world! Click here

In [ ]:
# 2. Removing numbers/digits
def replace_numbers(text):
    result = re.sub(r'\d+', '<phone number>', text)
    return result

In [ ]:
input_numbers_text = "Her phone 554444 number is 0123456789, and my phone number is 0987654321"
replace_numbers(input_numbers_text)

'Her phone 554444 number is <phone number>, and my phone number is <phone number>'

In [30]:
# 3. Convert the numbers into words
import inflect 
p = inflect.engine()

In [31]:
def convert_number(text):
    #split string into list of words
    temp_str = text.split()
    # initialize empty list
    new_string = []
    
    for word in temp_str:
        # if word is a digit, convert the digit to the word in letters and append into the new_string list
        if word.isdigit():
            temp = p.number_to_words(word)
            new_string.append(temp)
            
        # append the word as it is 
        else:
            new_string.append(word)
            
    #join the words of new_string to form a string
    temp_str = ' '.join(new_string)
    return temp_str

In [32]:
input = "There are 3 balls in this bag, and 12 in the other one."
convert_number(input)

'There are three balls in this bag, and twelve in the other one.'

In [33]:
# 4. Removing punctuation & special chars
regular_punct = list(string.punctuation)
print(regular_punct)

['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']

In [34]:
def remove_punctuation(text, punct_list):
    for punc in punct_list :
        if punc in text:
            text = text.replace(punc,'')
    return text.strip()

In [35]:
remove_punctuation("Hey, @Lisa, did you know that the summer break is coming? Amazing right!! It's only 5 more days !!", regular_punct)

'Hey Lisa did you know that the summer break is coming Amazing right Its only 5 more days'

In [36]:
# 5. Handling double whitespace from text

def remove_whitespace(text):
    return " ".join(text.split())

input_ws = "we don't need the   given     questions."
remove_whitespace(input_ws)

"we don't need the given questions."

In [37]:
# 6. Handling emoji/emoticon ---> for sentiment analysis, emoji/emoticon is usually not removed

def remove_emojis_regex(text):
    # remove emojis using Unicode emoji ranges.
    # Unicode ranges for emojis
   emoji_pattern = re.compile("["
    u"\U0001F600-\U0001F64F"  # emoticons
    u"\U0001F300-\U0001F5FF"  # symbols & pictographs
    u"\U0001F680-\U0001F6FF"  # transport & map symbols
    u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
    u"\U00002702-\U000027B0"  # dingbats
    u"\U000024C2-\U0001F251"
    u"\U0001f926-\U0001f937"
    u"\U00010000-\U0010ffff"
    "]+", flags=re.UNICODE)
   
   return emoji_pattern.sub(r'', text)

In [38]:
emoji_text = "Hello! 😃 How are you ? 🎉 I'm in NYC 🇺🇸"

cleaned_emoji = remove_emojis_regex(emoji_text)
cleaned_emoji

"Hello!  How are you ?  I'm in NYC "

In [39]:
import emoji #we can also do it with a library

In [40]:
def remove_emojis_emoji_library(text):
    return emoji.replace_emoji(text, replace='')

def replace_emojis_with_text(text):
    #with their text description
    return emoji.demojize(text)


emojis_text = "I LOVE PYTHON! 🐍💓 Let's code ! 💻🤏"

no_emojis = remove_emojis_emoji_library(emojis_text)
emojis_replaced = replace_emojis_with_text(emojis_text)

print(no_emojis)
print(emojis_replaced)

I LOVE PYTHON!  Let's code !
I LOVE PYTHON! :snake::beating_heart: Let's code ! :laptop::pinching_hand:

In [41]:
# 7. Removal of URLs or other irrelevant hints

#Define a regex pattern to match URLs
url_pattern = re.compile(r'https?://\S+')

#Define a function to remove URLs from text
def remove_urls(text):
    return url_pattern.sub('', text) # we remove the url

text_url = "Visit https://www.google.com for more information."
remove_urls(text_url)

'Visit  for more information.'

In [ ]:
url_pattern = []
url_pattern.append(re.compile(r'https?://\S+'))
url_pattern.append(re.compile(r'http?://\S+'))
url_pattern.append(re.compile(r'www.\S+'))

def replace_more_urls(text):
    for pattern in url_pattern:
        text= pattern.sub('<this link>', text) # we replace the url with <this link>
    return text

more_url_text = "Visit www.google.com for info"
replace_more_urls(more_url_text)

'Visit <this link> for info'

# 5.Tokenization

In NLP, tokenization is the text preprocessing task of reaking up text into smaller components of text (tokens)

See other library : spaCy tokenizer

In [43]:
text = "This is a text to tokenize"
tokenized = nltk.word_tokenize(text=text)

print(f"Result from tokenization : {tokenized}")

Result from tokenization : ['This', 'is', 'a', 'text', 'to', 'tokenize']

# 6. Stopwords removal

Stopwords are words that do not contribute to the meaning of a sentence. Hence, they can safely be removed without causing any change in the meaning 
of the sentence. The NLTK library has a set of stopwords and we can use these to remove stopwrods from our text and return a list of word tokens

In [44]:
# Stopwords removal
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\alexandre.karneff\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Package stopwords is already up-to-date!

True

In [45]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'be', 'here', 'in', "won't", 'our', "shouldn't", 'do', 'wasn', 'no', 'under', 'to', 'during', 'the', 'all', 'couldn', 'too', "they'll", 'was', "you've", 'that', 'o', 'from', 'same', 'itself', 'how', 'nor', "they've", 'himself', 'yourself', 'a', 'off', 'you', 'wouldn', 'each', 'myself', 'whom', 'yours', 'did', 'below', 'ain', 'at', 'll', 'mightn', "they're", "don't", 'shan', "wasn't", "wouldn't", 'into', 'only', 'until', 'we', "doesn't", 'not', 'with', "you'd", 'both', 'doesn', "we've", 'on', "mightn't", 'doing', "haven't", 'herself', 'ours', 'most', 'just', 'ourselves', 'further', 'hasn', 'them', 'him', 'through', 'and', 'this', 'as', "she'll", "we're", 'it', 'but', 'up', 's', 'won', 'where', 'her', 'between', "hasn't", 'can', "i've", 'he', 'by', 'am', 'm', 'there', 'his', "we'd", "i'd", 'weren', "aren't", 'before', 'now', 'is', 'needn', 'these', 'its', 're', 'than', 'more', 'she', 'aren', 'are', 'or', 'for', 'down', "he'd", 'then', 'why', 'once', "didn't", 'so', 'who', "i'll", 'against', "it'll", 'those', 'hadn', "they'd", 'which', 'because', 'me', 'above', 'their', 'having', 'of', 'other', "needn't", 'some', 'been', 'i', "isn't", 'shouldn', "that'll", 'don', "she'd", 'themselves', 'very', 'your', "shan't", 'over', "it'd", 'when', 'after', "he'll", "he's", 've', "she's", "should've", 'ma', "mustn't", 'being', 'didn', "we'll", 'yourselves', 'out', 'd', "hadn't", 'they', 'while', 'have', 'y', 'does', "you'll", 'has', 'own', 'were', "weren't", 'an', 'about', 'should', "you're", 'haven', 'my', 'any', 'mustn', 'will', 'isn', 'what', "it's", 'few', 'again', "couldn't", 'had', 'such', 'theirs', "i'm", 't', 'if', 'hers'}

In [46]:
# Customize the stopwords set
stop_words.add('test')
print(stop_words)

{'be', 'here', 'in', "won't", 'our', "shouldn't", 'do', 'wasn', 'no', 'under', 'to', 'during', 'the', 'all', 'couldn', 'too', "they'll", 'was', "you've", 'that', 'o', 'from', 'same', 'itself', 'how', 'nor', "they've", 'himself', 'yourself', 'a', 'off', 'you', 'wouldn', 'each', 'myself', 'whom', 'yours', 'did', 'below', 'ain', 'at', 'll', 'mightn', "they're", "don't", 'shan', "wasn't", "wouldn't", 'into', 'only', 'until', 'we', "doesn't", 'not', 'with', "you'd", 'both', 'doesn', "we've", 'on', "mightn't", 'doing', "haven't", 'herself', 'ours', 'most', 'just', 'ourselves', 'further', 'hasn', 'them', 'him', 'through', 'and', 'this', 'as', "she'll", 'test', "we're", 'it', 'but', 'up', 's', 'won', 'where', 'her', 'between', "hasn't", 'can', "i've", 'he', 'by', 'am', 'm', 'there', 'his', "we'd", "i'd", 'weren', "aren't", 'before', 'now', 'is', 'needn', 'these', 'its', 're', 'than', 'more', 'she', 'aren', 'are', 'or', 'for', 'down', "he'd", 'then', 'why', 'once', "didn't", 'so', 'who', "i'll", 'against', "it'll", 'those', 'hadn', "they'd", 'which', 'because', 'me', 'above', 'their', 'having', 'of', 'other', "needn't", 'some', 'been', 'i', "isn't", 'shouldn', "that'll", 'don', "she'd", 'themselves', 'very', 'your', "shan't", 'over', "it'd", 'when', 'after', "he'll", "he's", 've', "she's", "should've", 'ma', "mustn't", 'being', 'didn', "we'll", 'yourselves', 'out', 'd', "hadn't", 'they', 'while', 'have', 'y', 'does', "you'll", 'has', 'own', 'were', "weren't", 'an', 'about', 'should', "you're", 'haven', 'my', 'any', 'mustn', 'will', 'isn', 'what', "it's", 'few', 'again', "couldn't", 'had', 'such', 'theirs', "i'm", 't', 'if', 'hers'}

In [47]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    word_tokens = nltk.word_tokenize(text)
    
    #filter out the stopwords
    filtered_text = [word for word in word_tokens if word.lower() not in stop_words]
    
    return filtered_text

In [48]:
example_text = "This is a sample sentence and we are going to remove the stopwords from this."
print (f"Before remowing stopwords : {example_text}")
print (f"Aftere removing stopwords : {remove_stopwords(example_text)}")

Before remowing stopwords : This is a sample sentence and we are going to remove the stopwords from this.
Aftere removing stopwords : ['sample', 'sentence', 'going', 'remove', 'stopwords', '.']

# 7. Stemming & Lemmatization

Various algorithms form stemming : <br>
- Porter Stemmer <br>
- Snowball Stemmer <br>
- Lovins Stemmer

In [59]:
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
stemmer = PorterStemmer()

#stem words in the list of tokenized words
def stem_words(text):
    word_tokens = word_tokenize(text=text)
    stems = [stemmer.stem(word) for word in word_tokens]
    return stems

stem_text = "data science uses scientific methods algorithms and many types of processes"
stem_words(stem_text)

['data',
 'scienc',
 'use',
 'scientif',
 'method',
 'algorithm',
 'and',
 'mani',
 'type',
 'of',
 'process']

In [50]:
# Lemmatzation using NLTK
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\alexandre.karneff\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Package wordnet is already up-to-date!

True

In [51]:
lemmatizer = WordNetLemmatizer()

In [52]:
# Function to lemmatize words in the list of tokenized words
def lemma_words(text):
    word_tokens = word_tokenize(text)
    lemmas = [lemmatizer.lemmatize(word) for word in word_tokens]
    return lemmas

text = 'The quick brown foxes are jumping over the lazy dogs.'
lemma_words(text)

['The',
 'quick',
 'brown',
 'fox',
 'are',
 'jumping',
 'over',
 'the',
 'lazy',
 'dog',
 '.']

In [56]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --- ------------------------------------ 1.0/12.8 MB 12.7 MB/s eta 0:00:01
     --------------------------- ------------ 8.9/12.8 MB 30.4 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 30.6 MB/s  0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [61]:
# lemmatization using spaCy
import spacy

# load the spacy english model
nlp = spacy.load('en_core_web_sm')

text = "the quick brown foxes are jumping over the lazy dogs."

#Process the text using spaCy
doc = nlp(text)

#Extract lemmatized tokens
lemmatized_tokens = [token.lemma_ for token in doc]

#Join the lemmatized tokens into a sentence
lemmatized_text = ' '.join(lemmatized_tokens)

print(f"Original text : {text}")
print(f"Text lemmatized with spaCy : {lemmatized_text}")

Original text : the quick brown foxes are jumping over the lazy dogs.
Text lemmatized with spaCy : the quick brown fox be jump over the lazy dog .

# Coding Exercise

NLP coding exercicse

In [170]:
import pandas as pd

In [171]:
data = pd.read_csv('data/SMS_test.csv', encoding='latin-1')

In [172]:
data

     S. No.                                       Message_body     Label
0         1  UpgrdCentre Orange customer, you may now claim...      Spam
1         2  Loan for any purpose £500 - £75,000. Homeowner...      Spam
2         3  Congrats! Nokia 3650 video camera phone is you...      Spam
3         4  URGENT! Your Mobile number has been awarded wi...      Spam
4         5  Someone has contacted our dating service and e...      Spam
..      ...                                                ...       ...
120     121  7 wonders in My WORLD 7th You 6th Ur style 5th...  Non-Spam
121     122  Try to do something dear. You read something f...  Non-Spam
122     123  Sun ah... Thk mayb can if dun have anythin on....  Non-Spam
123     124  SYMPTOMS when U are in love: "1.U like listeni...  Non-Spam
124     125  Great. Have a safe trip. Dont panic surrender ...  Non-Spam

[125 rows x 3 columns]

In [173]:
data.dtypes

S. No.          int64
Message_body      str
Label             str
dtype: object

a.Text Normalization

In [174]:
data["Case_Normalization"] = data.Message_body.apply(text_lowercase)

In [175]:
data

,S. No.,Message_body,Label,Case_Normalization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congrats! nokia 3650 video camera phone is you...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...
4,5,Someone has contacted our dating service and e...,Spam,someone has contacted our dating service and e...
...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world 7th you 6th ur style 5th...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... thk mayb can if dun have anythin on....
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when u are in love: ""1.u like listeni..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. dont panic surrender ...

In [176]:
data.Case_Normalization = data.Case_Normalization.apply(contractions.fix)

In [177]:
data

,S. No.,Message_body,Label,Case_Normalization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congrats! nokia 3650 video camera phone is you...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...
4,5,Someone has contacted our dating service and e...,Spam,someone has contacted our dating service and e...
...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world 7th you 6th you are styl...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... thk mayb can if dun have anythin on....
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...

In [178]:
data.Case_Normalization = data.Case_Normalization.apply(correct_with_textblob)

In [179]:
data

,S. No.,Message_body,Label,Case_Normalization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...
...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...

b. noise removal

In [180]:
data_nr = data.copy()

In [181]:
data_nr["Noise_Removal"] = data_nr.Case_Normalization.apply(remove_html_tags_regex)

In [182]:
data_nr

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...","upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...","loan for any purpose £500 - £75,000. homeowner..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress! nikita 3650 video camera phone is yo...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent! your mobile number has been awarded wi...
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...
...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,7 wonders in my world th you th you are style ...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear. you read something f...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah... the may can if dun have anything on....
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...","symptoms when you are in love: ""1.you like lis..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great. have a safe trip. do not panic surrende...

In [183]:
def remove_numbers(text):
    result = re.sub(r'\d+','', text)
    return result

In [184]:
data_nr.Noise_Removal = data_nr.Noise_Removal.apply(remove_numbers)

In [185]:
data_nr

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...","upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...","loan for any purpose £ - £,. homeowners + tena..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress! nikita video camera phone is your c...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent! your mobile number has been awarded wi...
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...
...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,wonders in my world th you th you are style t...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear. you read something f...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah... the may can if dun have anything on....
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...","symptoms when you are in love: "".you like list..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great. have a safe trip. do not panic surrende...

In [188]:
data_nr.Noise_Removal = data_nr.Noise_Removal.apply(lambda text: remove_punctuation(text, punct_list=regular_punct))

In [189]:
data_nr

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose £ £ homeowners tenants ...
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress nikita video camera phone is your ca...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...
...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,wonders in my world th you th you are style th...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear you read something fo...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah the may can if dun have anything on the...
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...",symptoms when you are in love you like listeni...
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great have a safe trip do not panic surrender all

In [190]:
def remove_special_chars(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

In [191]:
data_nr.Noise_Removal = data_nr.Noise_Removal.apply(remove_special_chars)

In [193]:
data_nr

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose homeowners tenants we...
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress nikita video camera phone is your ca...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...
...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,wonders in my world th you th you are style th...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear you read something fo...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah the may can if dun have anything on the...
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...",symptoms when you are in love you like listeni...
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great have a safe trip do not panic surrender all

In [194]:
url_pattern = []
url_pattern.append(re.compile(r'https?://\S+'))
url_pattern.append(re.compile(r'http?://\S+'))
url_pattern.append(re.compile(r'www.\S+'))

def remove_more_urls(text):
    for pattern in url_pattern:
        text= pattern.sub('', text) # we replace the url with nothing
    return text

In [195]:
data_nr.Noise_Removal = data_nr.Noise_Removal.apply(remove_more_urls)

In [196]:
data_nr.Noise_Removal = data_nr.Noise_Removal.apply(remove_whitespace)

In [197]:
data_nr

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose homeowners tenants welcom...
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress nikita video camera phone is your cal...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...
...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,wonders in my world th you th you are style th...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear you read something fo...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah the may can if dun have anything on the...
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...",symptoms when you are in love you like listeni...
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great have a safe trip do not panic surrender all

c.tokenization

In [216]:
data_tkn = data_nr.copy()

In [217]:
data_tkn["Tokenization"] = data_tkn.Noise_Removal.apply(nltk.word_tokenize)

In [218]:
data_tkn

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal,Tokenization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...,"[upgrdcentre, orange, customer, you, may, now,..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose homeowners tenants welcom...,"[loan, for, any, purpose, homeowners, tenants,..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress nikita video camera phone is your cal...,"[congress, nikita, video, camera, phone, is, y..."
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...,"[urgent, your, mobile, number, has, been, awar..."
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...,"[someone, has, contracted, our, dating, servic..."
...,...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,wonders in my world th you th you are style th...,"[wonders, in, my, world, th, you, th, you, are..."
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear you read something fo...,"[try, to, do, something, dear, you, read, some..."
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah the may can if dun have anything on the...,"[sun, ah, the, may, can, if, dun, have, anythi..."
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...",symptoms when you are in love you like listeni...,"[symptoms, when, you, are, in, love, you, like..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great have a safe trip do not panic surrender all,"[great, have, a, safe, trip, do, not, panic, s..."

d.Stopwords

In [259]:
data_stopw = data_tkn.copy()

In [260]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\alexandre.karneff\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Package stopwords is already up-to-date!

True

In [261]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    word_tokens = nltk.word_tokenize(text)
    
    #filter out the stopwords
    filtered_text = [word for word in word_tokens if word.lower() not in stop_words]
    
    return filtered_text

In [262]:
data_stopw["Stopwords"] = data_stopw.Noise_Removal.apply(remove_stopwords)

In [263]:
data_stopw

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal,Tokenization,Stopwords
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...,"[upgrdcentre, orange, customer, you, may, now,...","[upgrdcentre, orange, customer, may, claim, fr..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose homeowners tenants welcom...,"[loan, for, any, purpose, homeowners, tenants,...","[loan, purpose, homeowners, tenants, welcome, ..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress nikita video camera phone is your cal...,"[congress, nikita, video, camera, phone, is, y...","[congress, nikita, video, camera, phone, call,..."
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...,"[urgent, your, mobile, number, has, been, awar...","[urgent, mobile, number, awarded, prize, guara..."
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...,"[someone, has, contracted, our, dating, servic...","[someone, contracted, dating, service, entered..."
...,...,...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,wonders in my world th you th you are style th...,"[wonders, in, my, world, th, you, th, you, are...","[wonders, world, th, th, style, th, smile, th,..."
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear you read something fo...,"[try, to, do, something, dear, you, read, some...","[try, something, dear, read, something, exam]"
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah the may can if dun have anything on the...,"[sun, ah, the, may, can, if, dun, have, anythi...","[sun, ah, may, dun, anything, book, e, lesson,..."
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...",symptoms when you are in love you like listeni...,"[symptoms, when, you, are, in, love, you, like...","[symptoms, love, like, listening, songs, get, ..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great have a safe trip do not panic surrender all,"[great, have, a, safe, trip, do, not, panic, s...","[great, safe, trip, panic, surrender]"

e-1. Stemming

In [264]:
data_stemmed = data_stopw.copy()

In [265]:
stemmer = PorterStemmer()

#stem words in the list of tokenized words
def stem_words(text):
    word_tokens = word_tokenize(text=text)
    stems = [stemmer.stem(word) for word in word_tokens]
    return stems

In [266]:
data_stemmed["Stemming"] = data_stemmed.Stopwords.apply(lambda words: [stemmer.stem(w) for w in words])

In [267]:
data_stemmed

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal,Tokenization,Stopwords,Stemming
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...,"[upgrdcentre, orange, customer, you, may, now,...","[upgrdcentre, orange, customer, may, claim, fr...","[upgrdcentr, orang, custom, may, claim, free, ..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose homeowners tenants welcom...,"[loan, for, any, purpose, homeowners, tenants,...","[loan, purpose, homeowners, tenants, welcome, ...","[loan, purpos, homeown, tenant, welcom, previo..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress nikita video camera phone is your cal...,"[congress, nikita, video, camera, phone, is, y...","[congress, nikita, video, camera, phone, call,...","[congress, nikita, video, camera, phone, call,..."
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...,"[urgent, your, mobile, number, has, been, awar...","[urgent, mobile, number, awarded, prize, guara...","[urgent, mobil, number, award, prize, guarante..."
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...,"[someone, has, contracted, our, dating, servic...","[someone, contracted, dating, service, entered...","[someon, contract, date, servic, enter, phone,..."
...,...,...,...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,wonders in my world th you th you are style th...,"[wonders, in, my, world, th, you, th, you, are...","[wonders, world, th, th, style, th, smile, th,...","[wonder, world, th, th, style, th, smile, th, ..."
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear you read something fo...,"[try, to, do, something, dear, you, read, some...","[try, something, dear, read, something, exam]","[tri, someth, dear, read, someth, exam]"
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah the may can if dun have anything on the...,"[sun, ah, the, may, can, if, dun, have, anythi...","[sun, ah, may, dun, anything, book, e, lesson,...","[sun, ah, may, dun, anyth, book, e, lesson, e,..."
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...",symptoms when you are in love you like listeni...,"[symptoms, when, you, are, in, love, you, like...","[symptoms, love, like, listening, songs, get, ...","[symptom, love, like, listen, song, get, stop,..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great have a safe trip do not panic surrender all,"[great, have, a, safe, trip, do, not, panic, s...","[great, safe, trip, panic, surrender]","[great, safe, trip, panic, surrend]"

e-2. Lemmatization

In [268]:
data_lemmatized = data_stemmed.copy()

In [269]:
data_lemmatized['Lemmatization'] = data_lemmatized.Stopwords.apply(lambda words: [nlp(w)[0] for w in words])

In [270]:
data_lemmatized

,S. No.,Message_body,Label,Case_Normalization,Noise_Removal,Tokenization,Stopwords,Stemming,Lemmatization
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim...",upgrdcentre orange customer you may now claim ...,"[upgrdcentre, orange, customer, you, may, now,...","[upgrdcentre, orange, customer, may, claim, fr...","[upgrdcentr, orang, custom, may, claim, free, ...","[upgrdcentre, orange, customer, may, claim, fr..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner...",loan for any purpose homeowners tenants welcom...,"[loan, for, any, purpose, homeowners, tenants,...","[loan, purpose, homeowners, tenants, welcome, ...","[loan, purpos, homeown, tenant, welcom, previo...","[loan, purpose, homeowners, tenants, welcome, ..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congress! nikita 3650 video camera phone is yo...,congress nikita video camera phone is your cal...,"[congress, nikita, video, camera, phone, is, y...","[congress, nikita, video, camera, phone, call,...","[congress, nikita, video, camera, phone, call,...","[congress, nikita, video, camera, phone, call,..."
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...,urgent your mobile number has been awarded wit...,"[urgent, your, mobile, number, has, been, awar...","[urgent, mobile, number, awarded, prize, guara...","[urgent, mobil, number, award, prize, guarante...","[urgent, mobile, number, awarded, prize, guara..."
4,5,Someone has contacted our dating service and e...,Spam,someone has contracted our dating service and ...,someone has contracted our dating service and ...,"[someone, has, contracted, our, dating, servic...","[someone, contracted, dating, service, entered...","[someon, contract, date, servic, enter, phone,...","[someone, contracted, dating, service, entered..."
...,...,...,...,...,...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world th you th you are style ...,wonders in my world th you th you are style th...,"[wonders, in, my, world, th, you, th, you, are...","[wonders, world, th, th, style, th, smile, th,...","[wonder, world, th, th, style, th, smile, th, ...","[wonders, world, th, th, style, th, smile, th,..."
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...,try to do something dear you read something fo...,"[try, to, do, something, dear, you, read, some...","[try, something, dear, read, something, exam]","[tri, someth, dear, read, someth, exam]","[try, something, dear, read, something, exam]"
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... the may can if dun have anything on....,sun ah the may can if dun have anything on the...,"[sun, ah, the, may, can, if, dun, have, anythi...","[sun, ah, may, dun, anything, book, e, lesson,...","[sun, ah, may, dun, anyth, book, e, lesson, e,...","[sun, ah, may, dun, anything, book, e, lesson,..."
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when you are in love: ""1.you like lis...",symptoms when you are in love you like listeni...,"[symptoms, when, you, are, in, love, you, like...","[symptoms, love, like, listening, songs, get, ...","[symptom, love, like, listen, song, get, stop,...","[symptoms, love, like, listening, songs, get, ..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. do not panic surrende...,great have a safe trip do not panic surrender all,"[great, have, a, safe, trip, do, not, panic, s...","[great, safe, trip, panic, surrender]","[great, safe, trip, panic, surrend]","[great, safe, trip, panic, surrender]"